spring:
  config:
    import: classpath:.env.local[.properties]
  datasource:
    url: jdbc:mysql://${MYSQL_URL}?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  server:
    port: 8080